language: ruby
# before_install:
#   - sudo apt-get update
#   - sudo apt-get install postgresql-server-dev-9.3
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql
  - sudo apt-get install postgresql-server-dev-9.3
  - sudo apt-get install ibpq-dev
rvm:
  - 2.0.0-p247